module.exports = {
  roomsError: 'rooms:error',
  cardsDragged: 'cards:dragged',
  cardsDropped: 'cards:dropped',
  cardsSwapped: 'cards:swapped',
  cards_updated: 'cards:updated',
  cards_declared: 'cards:declared',
  cards_laidoff: 'cards:laidoff',
  roomsJoined: 'rooms:joined',
  peersJoined: 'peers:joined',
  peersConnect: 'peers:connect',
  peersDisconnect: 'peers:disconnect',
  peersTrunToPick: 'peers:trunToPick',
  peersDroppedCard: 'peers:dropped:card',
}
